# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba433f7b3f1fd6fa3fa3a42ecaf679e49bf3986cafe5660bd81af42b6e58aaf1245adbb1c4e71a785a5cc09d792f9689e7de74544679135fc00d9e1c880e0eed

test:
  secret_key_base: 680f4b13f9e636be001f73c42206e8851f4514ad4524a7fc5c79437083c312c38e1b7b219c64874a10ac7173883d7fae53de626bba307bc07b33590bcb4d62e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
